import type { Diagnostic, IntentPage, IntentSpec, Plan, PlanStep } from "./types.js";
import type { WorkspaceReader } from "./workspace.js";
import { approxLinesChanged } from "./patch.js";

function normalizeRoute(routeHint: string) {
  if (!routeHint.startsWith("/")) return `/${routeHint}`;
  return routeHint;
}

function pascalSafe(name: string) {
  return name.replace(/[^a-zA-Z0-9]/g, "");
}

function appPageFileFromRoute(route: string) {
  if (route === "/") return "app/page.tsx";
  const seg = route.replace(/^\/+/, "").replace(/\/+$/, "");
  return `app/${seg}/page.tsx`;
}

function escapeHtml(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function pageTemplate(page: IntentPage) {
  const title = page.title;
  const sections = page.sections ?? [
    { type: "heading", text: title },
    { type: "paragraph", text: "Generated by WebSpec." },
  ];

  const body = sections
    .map((s) => {
      if (s.type === "heading") return `<h1 className=\"text-2xl font-semibold\">${escapeHtml(s.text)}</h1>`;
      if (s.type === "callout") return `<div className=\"rounded-lg border p-4\">${escapeHtml(s.text)}</div>`;
      return `<p className=\"opacity-80\">${escapeHtml(s.text)}</p>`;
    })
    .join("\n      ");

  const componentName = `${pascalSafe(page.name)}Page`;
  return `export default function ${componentName}() {
  return (
    <main className="mx-auto max-w-3xl p-6 space-y-4">
      ${body}
    </main>
  );
}
`;
}

export async function compileNextAppRouterIntent(
  intent: IntentSpec,
  ws: WorkspaceReader
): Promise<{ plan?: Plan; diagnostics: Diagnostic[] }> {
  const diagnostics: Diagnostic[] = [];
  const steps: PlanStep[] = [];

  for (const p of intent.intent.pages) {
    const route = normalizeRoute(p.routeHint);
    const file = appPageFileFromRoute(route);

    if (!(await ws.exists(file))) {
      steps.push({ kind: "writeFile", path: file, content: pageTemplate(p) });
    }

    steps.push({ kind: "assertFileExists", path: file });
    steps.push({ kind: "assertFileContains", path: file, needle: "export default function" });
  }

  const touched = new Set<string>();
  let newFiles = 0;
  for (const s of steps) {
    if ("path" in s) touched.add(s.path);
    if (s.kind === "writeFile") newFiles += 1;
  }

  const plan: Plan = {
    target: "nextjs-app-router-shadcn-tailwind4",
    steps,
    predictedImpact: {
      filesTouched: touched.size,
      newFiles,
      routerTouched: false,
      configTouched: false,
      depsTouched: false,
      approxLinesChanged: approxLinesChanged({
        target: "nextjs-app-router-shadcn-tailwind4",
        steps,
        predictedImpact: {
          filesTouched: 0,
          newFiles: 0,
          routerTouched: false,
          configTouched: false,
          depsTouched: false,
          approxLinesChanged: 0,
        },
      }),
    },
  };

  return { plan, diagnostics };
}
